name: election_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
 

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc:
  flutter_spinkit: ^5.2.0
  numpad_layout: ^0.0.3
  flutter_secure_storage: any
  # for linux flutter_secure_storage needs libsecret-1-dev and libjsoncpp-dev on your machine to
  # build the project, and libsecret-1-0 and libjsoncpp1 to run the application
 # (add it as a dependency after packaging your app).
  twilio: ^0.0.2
  http: ^0.13.6
  another_flushbar: ^1.12.30
  dropdown_button2: ^2.3.9
  device_info_plus: ^8.2.0
  awesome_dialog: ^3.1.0
  flutter_svg: ^2.0.5
  crypto: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:
     uses-material-design: true
     assets:
      - assets/images/logo.png
      - assets/images/kalonzo.jpg
      - assets/images/ruto.png
      - assets/images/rigathi.jpg
      - assets/images/not_found.svg